changelog:
  exclude:
    labels:
      - "deployment: development"
      - "deployment: cbt"
      - "deployment: production"
  categories:
    - title: todo
      labels:
        - "project: todo"
    - title: notes
      labels:
        - "project: notes"
    # This should be the last.
    - title: Other Changes
      labels:
        - "*"
