apiVersion: v1
kind: ConfigMap
metadata:
  namespace: notes
  name: notes-api-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  config.yaml: |
    service_name: notes-api
    port: 3001
