name: Update latest image

on:
  push:
    branches:
      - main

concurrency:
  group: update-latest
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      force: true
      image_tag: latest
      push: true
      project: "*"
  restart:
    needs: build
    uses: ./.github/workflows/restart.yaml
    secrets: inherit
    with:
      environment: "*"
      project: "*"
